{{- if ne .Release.Namespace "default" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "suparship.namespace" . }}
  labels:
    {{- include "suparship.labels" . | nindent 4 }}
{{- end }}
