apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
  - name: acrsharedsouthcentralusbiglysales.azurecr.io/biglysales-voiceai-livekit
    newTag: "60442518"

namespace: voiceai

commonLabels:
  environment: production

patches:
- path: patch-express-caller.yaml
- path: patch-followup.yaml
- path: patch-outbound-caller.yaml
- path: patch-retry-caller.yaml
- path: patch-inbound-caller.yaml
- path: patch-track-mixer-worker.yaml
- path: patch-web-scaler.yaml
- path: patch-web.yaml
