apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: op-connect-token-staging
  namespace: external-secrets-system
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    token: AgCWoslVSvxmjcD8q9s4Val//49gLeyj2fBYgjFZPmQuv/Okm26Zq6Ci0b3D9XOfGo8si+7vftayPB3emMJEvo/n7frTrQ96peezyvVPfy2gpRemkvzZAelafu0ln7tj8HlyDlige2Dz2CN9uIiu9Dp+f+itI3o52ixXraVvUq2OH2IdnfB+H967oYB1NoxuP4m83F5xHItC2x8IIKMNht4Mkpg+WvCDzPYMXlYQlw/her76TPKW+njiun87G3Txh5J5l5CXT5QYGGj6FpWixZpS5tMP0XiQJCdJZtyC92JmxlzKRMrez7+/bS9LBVgfieZ73BkWCa0biqUTblW1itROfM9fChsmwps+pDDyX2Pl6We1csg73GateUg6sDIdnWyhzj6YGf5P82S2FheT+D4cLtUXc1buzJge5LD13ZWAak5wsf8adaPehS6aABzj8MPpjfUlC6ENrPrbuOufDU1NsIfwr61OrXFJmE26ywTkQ8gvNwpoqh+/b1rppQUIM/Py8wuMdVN/X8wRwjhJiFJLa/Tk+R7O1PF9jo21us0EqLDg2sHhPKd1x+r2aGrg/GEyvcqT76/TSbAtULX3cQNZR1NkSgNAbqyYWeCzeqq7B5gGhtG8SqhJ53cJnvigP4QFROJkqrhWQKOagY+RoLxLJj6Zro3CZU+K1bdD8ToPCCcSAhEYSU+X/1fxJ5OPRvpn++zUc56k+HW3S41KwZxWQxQbx1SkIurxzCm7/0U500BX27WZANNopAc62gIdOBjwtWKGoKWWq9lRnvOP/NXW2a3ywJFsayb+YCNubm5E0DUcUfo/88Ngvlh0VsKZR0dwGYnhoR/S0hjD9567Cc8nkAZXRv9p20/cDQJPM2XKu2ADD5Gnde5+1zBTFKZC0E2djBQXl0v0ZtWhgD2s44kDMnHw+TKQcF9hxVknBONxfb1/5qeULM18NrVaRgp+aAww6SKzCXzgBM70ta/xdwAo0W5Ky7aR9MrI049uPmNphxxbB1KDGd1Z2CRS3ZwQveT51+blknyOlzSGx8yBYBllidw1bgNRAxVpWmtdNRBeIAm+EOnl9AAK8AqBy/O/z01MasQjsmr38KSEULXRidwzE7QbsWX4ou4WLVpjx4Q7vrGkT4Nn2v+Dax0KMwQZCPTbyeUlCmJiWG3wEYzeajXNLWmj4dyqYIoYWFlnWNt/X2/JCzNpAzDpvmmWUHSyqgjdCPB1ehqVGsISForqA1dMU/EwfxhY6yBd7x3cfmFI9+eupqqKJPhl5QgfIkKV1WBYl52BdORiRg5AF0wQhFBlvxbdB5NADEk63bnifX8nG4j0aEuwr9Ug3CJwgNjg9CnNccTqy+q80P5BqjAQn66gwe5dXpEg0uZ4QUO+deaOqSu70uwsZXdIoZWcdRYb1orRY/jquEdw62ofBCDSDqaB4hEZ8Sqw0khkXkJmDCxFazpePUwDEP7Sfue8v+Ne8GqgmmP0asaWcMwilcNiBlDJfo4MZb46Yfm+abQtJeirv5LMJ4iVlc1GVmu+WNoB0TrM+5SMoPnz7FqQV4aKIM4gtqQ=
  template:
    metadata:
      creationTimestamp: null
      name: op-connect-token-staging
      namespace: external-secrets-system
      labels:
        app.kubernetes.io/managed-by: "suparship"
        suparship.io/env: "staging"
    type: Opaque
