---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiceai-livekit-agent-server-followup-caller
spec:
  template:
    spec:
      containers:
        - name: voiceai-livekit-agent-server
          resources:
            requests:
              # 3.4 cpu to be able to pack 2 pods on the 8 core node and avoid 50% resource waste
              cpu: "4000m"
              # on prod max usage 4880, set request to make this value 70% of max: 6980Mi
              # OOM on 6980Mi, add 500Mi to avoid future OOMs
              # OOM on 7480Mi, add 500Mi to avoid future OOMs: 7980Mi
              # OOM on 7980Mi, add 500Mi to avoid future OOMs: 8480Mi
              memory: "15360Mi"
              # retry-caller had eviction on 200Mi disk limit
              ephemeral-storage: "400Mi"
            limits:
              # same as requests to garanteed memory and avoid node level OOM
              memory: "15360Mi"
              ephemeral-storage: "400Mi"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: voiceai-livekit-agent-server-followup-caller
spec:
  scaleTargetRef:
    name: voiceai-livekit-agent-server-followup-caller
  minReplicaCount: 0
  maxReplicaCount: 12
