---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiceai-livekit-agent-server-followup-caller
spec:
  template:
    spec:
      containers:
      - name: voiceai-livekit-agent-server
        env:
        - name: MAX_AGENTS
          value: "10"
        - name: AG__NUM_IDLE_PROCESSES
          value: "10"
        - name: VALKEY_INTERNAL_URL
          value: "redis://livekit-redis.internal.aws.biglysalesstaging.com:6379/0"
        envFrom:
        - secretRef:
            name: voiceai-livekit-env
        - secretRef:
            name: voiceai-livekit-self-hosted-env
