apiVersion: v1
kind: Service
metadata:
  name: valkey-internal
  labels:
    app: valkey-internal
spec:
  clusterIP: None
  ports:
  - name: valkey
    port: 6379
    targetPort: valkey
  selector:
    app: valkey-internal
