apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
  - name: acrsharedsouthcentralusbiglysales.azurecr.io/biglysales-voiceai-livekit
    newTag: "896c30f"

namespace: voiceai

commonLabels:
  environment: staging
