#!/usr/bin/env bash
# hack/deploy-demo-app.sh — deploy the hello demo app to the kind cluster.
#
# Manually commits an ArgoCD Application manifest to the gitops repo so the
# suparship-apps root App of Apps picks it up and deploys it.
#
# This is the stop-gap workflow until the suparship server auto-commits on app
# creation. It demonstrates the full GitOps loop:
#
#   this script → gitops repo (Gitea) → ArgoCD suparship-apps → hello-staging ns
#
# App:       hello
# Project:   demo
# Env:       staging
# Namespace: hello-staging
# Image:     nginx:alpine  (port 80, health at /)
# Ingress:   http://hello.localhost:8880
#
# Prerequisites:
#   task dev:cluster:bootstrap
#   task dev:cluster:ingress
#   task dev:cluster:argocd
#   task dev:cluster:gitea
#
# Usage:
#   ./hack/deploy-demo-app.sh
#   task demo:deploy
set -euo pipefail

GITEA_HOST_URL="http://gitea.localhost:8880"
GITEA_ADMIN_USER="gitops"
GITEA_ADMIN_PASS="gitops-dev-only"
GITOPS_REPO_ORG="gitops"
GITOPS_REPO_NAME="gitops"
GITEA_CLUSTER_URL="http://gitea-http.gitea.svc.cluster.local:3000"

APP_NAME="hello"
PROJECT="demo"
ENV_NAME="staging"
NAMESPACE="${APP_NAME}-${ENV_NAME}"
ARGOCD_NAMESPACE="argocd"

APP_PATH="gitops-output/${PROJECT}/${APP_NAME}/${ENV_NAME}"
APP_FILE="${APP_PATH}/argocd-app.yaml"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# ── Helpers ───────────────────────────────────────────────────────────────
info()  { printf "  \033[0;36m%s\033[0m\n" "$*"; }
ok()    { printf "  \033[0;32m✓\033[0m  %s\n" "$*"; }
skip()  { printf "  \033[0;33m–\033[0m  %s\n" "$*"; }
die()   { printf "  \033[0;31mERROR:\033[0m %s\n" "$*" >&2; exit 1; }

# ── Banner ────────────────────────────────────────────────────────────────
echo ""
echo "  suparShip — deploy demo app  (hello / staging)"
echo "  ──────────────────────────────────────────────────────────────────"
echo ""

# ── 1. Prereq checks ─────────────────────────────────────────────────────
info "Checking prerequisites..."
for cmd in kubectl git curl; do
  command -v "$cmd" >/dev/null 2>&1 && ok "$cmd" || die "'$cmd' not found"
done

kubectl get application suparship-apps -n "${ARGOCD_NAMESPACE}" >/dev/null 2>&1 \
  || die "suparship-apps ArgoCD Application not found. Run: task dev:cluster:gitea"
echo ""

# ── 2. Check /etc/hosts ───────────────────────────────────────────────────
if grep -q "hello.localhost" /etc/hosts 2>/dev/null; then
  ok "/etc/hosts has hello.localhost"
else
  printf "  \033[0;33mWARNING:\033[0m hello.localhost not in /etc/hosts.\n"
  printf "  Add it manually to reach the app after deploy:\n"
  printf "    sudo sh -c 'echo \"127.0.0.1 hello.localhost\" >> /etc/hosts'\n"
fi
echo ""

# ── 3. Clone gitops repo ──────────────────────────────────────────────────
info "Cloning gitops repo..."
TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}"' EXIT

CLONE_URL="http://${GITEA_ADMIN_USER}:${GITEA_ADMIN_PASS}@${GITEA_HOST_URL#http://}/${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}.git"
git -c advice.detachedHead=false clone --quiet "${CLONE_URL}" "${TMPDIR}/gitops"
ok "cloned"
echo ""

cd "${TMPDIR}/gitops"
git config user.email "suparship-dev@local"
git config user.name  "suparShip Dev Bot"

# ── 4. Check if already deployed ─────────────────────────────────────────
if [ -f "${APP_FILE}" ]; then
  skip "${APP_FILE} already exists — app already deployed"
  echo ""
  echo "  To redeploy from scratch:"
  echo "    rm the file, push, and re-run this script."
  echo ""
  APP_EXISTS=true
else
  APP_EXISTS=false
fi

# ── 5. Commit argocd-app.yaml ─────────────────────────────────────────────
if [ "${APP_EXISTS}" = "false" ]; then
  info "Committing ${APP_FILE}..."

  mkdir -p "${APP_PATH}"

  cat > "${APP_FILE}" <<EOF
# ArgoCD Application: ${APP_NAME} / ${ENV_NAME}
# Generated by: hack/deploy-demo-app.sh
# In production this file is committed by the suparship server.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${APP_NAME}-${ENV_NAME}
  namespace: ${ARGOCD_NAMESPACE}
  labels:
    suparship.io/app: ${APP_NAME}
    suparship.io/project: ${PROJECT}
    suparship.io/env: ${ENV_NAME}
    suparship.io/env-type: staging
spec:
  project: default
  source:
    repoURL: ${GITEA_CLUSTER_URL}/${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}.git
    targetRevision: main
    path: charts/web-service
    helm:
      releaseName: ${APP_NAME}-${ENV_NAME}
      values: |
        replicaCount: 1
        image:
          repository: nginx
          tag: alpine
          pullPolicy: IfNotPresent
        port: 80
        healthCheck:
          path: /
        ingress:
          enabled: true
          className: nginx
          host: hello.localhost
        size: small
  destination:
    server: https://kubernetes.default.svc
    namespace: ${NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
EOF

  git add "${APP_FILE}"
  git commit --quiet -m "feat(demo): deploy hello app to staging

App:       ${APP_NAME}
Project:   ${PROJECT}
Env:       ${ENV_NAME}
Namespace: ${NAMESPACE}
Image:     nginx:alpine
Ingress:   http://hello.localhost:8880"

  git push --quiet origin main
  ok "pushed ${APP_FILE}"
  echo ""
fi

# ── 6. Wait for ArgoCD to pick it up ─────────────────────────────────────
info "Waiting for ArgoCD to create the hello-staging Application..."
FOUND=false
for i in $(seq 1 20); do
  if kubectl get application "${APP_NAME}-${ENV_NAME}" \
       -n "${ARGOCD_NAMESPACE}" >/dev/null 2>&1; then
    FOUND=true
    break
  fi
  printf "."
  sleep 5
done
echo ""

if [ "${FOUND}" = "false" ]; then
  die "hello-staging Application not created after 100s.
  Check: kubectl get application suparship-apps -n ${ARGOCD_NAMESPACE}
  Logs:  kubectl logs -n ${ARGOCD_NAMESPACE} -l app.kubernetes.io/name=argocd-application-controller"
fi
ok "hello-staging Application created by ArgoCD"
echo ""

# ── 7. Wait for the deployment to become healthy ──────────────────────────
info "Waiting for hello-staging deployment to be ready (up to 3 min)..."
kubectl wait deployment \
  --for=condition=available \
  --timeout=180s \
  -n "${NAMESPACE}" \
  -l "app.kubernetes.io/instance=${APP_NAME}-${ENV_NAME}" 2>/dev/null \
  || printf "  (deployment not yet available — check below)\n"
echo ""

# ── Done ──────────────────────────────────────────────────────────────────
cat <<EOF
  ──────────────────────────────────────────────────────────────────
  Demo app deployed!

  App        ${APP_NAME}
  Project    ${PROJECT}
  Env        ${ENV_NAME}
  Namespace  ${NAMESPACE}
  Image      nginx:alpine

  App URL (requires /etc/hosts entry):
    http://hello.localhost:8880

  ArgoCD Application:
    kubectl get application ${APP_NAME}-${ENV_NAME} -n ${ARGOCD_NAMESPACE}

  Pod status:
    kubectl get pods -n ${NAMESPACE}

  Logs:
    kubectl logs -n ${NAMESPACE} -l app.kubernetes.io/instance=${APP_NAME}-${ENV_NAME}

  GitOps commit:
    ${GITEA_HOST_URL}/${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}/src/branch/main/${APP_FILE}

EOF
