#!/usr/bin/env bash
# hack/init-gitops-repo.sh — bootstrap the gitops monorepo content in Gitea.
#
# Pushes the initial directory structure that suparship writes to and ArgoCD
# syncs from. Safe to re-run: checks for existing content before pushing.
#
# Monorepo layout after this script:
#
#   charts/
#     web-service/          ← Helm chart, copied from templates/web-service/chart/
#       Chart.yaml
#       values.yaml
#       templates/
#   gitops-output/
#     .gitkeep              ← placeholder; suparship writes per-app dirs here
#   README.md
#
# ArgoCD Application CRDs committed by suparship live at:
#   gitops-output/<project>/<app>/<env>/argocd-app.yaml
#
# Those Applications reference the chart at:
#   charts/<template-name>/
# with inline Helm values for that environment.
#
# Environment variables (all required — set by install-gitea.sh):
#   GITEA_HOST_URL       e.g. http://gitea.localhost:8880
#   GITEA_ADMIN_USER     e.g. gitops
#   GITEA_ADMIN_PASS     e.g. gitops-dev-only
#   GITOPS_REPO_ORG      e.g. gitops
#   GITOPS_REPO_NAME     e.g. gitops
#   GITEA_CLUSTER_URL    e.g. http://gitea-http.gitea.svc.cluster.local:3000
#   REPO_ROOT            absolute path to the suparship repo root
#
# Used by: hack/install-gitea.sh
set -euo pipefail

# ── Helpers ───────────────────────────────────────────────────────────────
info()  { printf "  \033[0;36m%s\033[0m\n" "$*"; }
ok()    { printf "  \033[0;32m✓\033[0m  %s\n" "$*"; }
skip()  { printf "  \033[0;33m–\033[0m  %s\n" "$*"; }
die()   { printf "  \033[0;31mERROR:\033[0m %s\n" "$*" >&2; exit 1; }

# ── Validate required env vars ────────────────────────────────────────────
: "${GITEA_HOST_URL:?GITEA_HOST_URL is required}"
: "${GITEA_ADMIN_USER:?GITEA_ADMIN_USER is required}"
: "${GITEA_ADMIN_PASS:?GITEA_ADMIN_PASS is required}"
: "${GITOPS_REPO_ORG:?GITOPS_REPO_ORG is required}"
: "${GITOPS_REPO_NAME:?GITOPS_REPO_NAME is required}"
: "${GITEA_CLUSTER_URL:?GITEA_CLUSTER_URL is required}"
: "${REPO_ROOT:?REPO_ROOT is required}"

GITOPS_REPO_HOST_URL="${GITEA_HOST_URL}/${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}.git"
# Credentials embedded in URL so git never prompts interactively.
CLONE_URL="http://${GITEA_ADMIN_USER}:${GITEA_ADMIN_PASS}@${GITEA_HOST_URL#http://}/${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}.git"

# ── Wait for Gitea to be reachable ───────────────────────────────────────
info "Waiting for Gitea at ${GITEA_HOST_URL} ..."
READY=false
for i in $(seq 1 20); do
  if curl -sf --max-time 3 "${GITEA_HOST_URL}/api/v1/version" >/dev/null 2>&1; then
    READY=true
    break
  fi
  printf "."
  sleep 3
done
echo ""
if [ "${READY}" = "false" ]; then
  die "Gitea did not become reachable at ${GITEA_HOST_URL} within 60s."
fi
ok "Gitea is reachable"
echo ""

# ── Ensure the gitops repo exists ────────────────────────────────────────
info "Ensuring gitops repo '${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}' exists..."

REPO_STATUS=$(curl -sf \
  "${GITEA_HOST_URL}/api/v1/repos/${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}" \
  -u "${GITEA_ADMIN_USER}:${GITEA_ADMIN_PASS}" \
  -o /dev/null -w "%{http_code}" 2>/dev/null || echo "000")

if [ "${REPO_STATUS}" = "200" ]; then
  skip "repo already exists"
else
  info "Repo not found (HTTP ${REPO_STATUS}) — creating via Gitea API..."
  CREATE_STATUS=$(curl -sf -X POST \
    "${GITEA_HOST_URL}/api/v1/user/repos" \
    -H "Content-Type: application/json" \
    -u "${GITEA_ADMIN_USER}:${GITEA_ADMIN_PASS}" \
    -d "{
      \"name\": \"${GITOPS_REPO_NAME}\",
      \"description\": \"suparShip GitOps manifests — generated by suparship\",
      \"private\": false,
      \"auto_init\": true,
      \"default_branch\": \"main\"
    }" \
    -o /dev/null -w "%{http_code}" 2>/dev/null || echo "000")
  if [ "${CREATE_STATUS}" = "201" ]; then
    ok "repo created"
  else
    die "Failed to create repo (HTTP ${CREATE_STATUS}). Is the Gitea user '${GITEA_ADMIN_USER}' correct?"
  fi
fi
echo ""

# ── Check if already initialised ─────────────────────────────────────────
info "Checking if gitops repo already has content..."

TREE_COUNT=$(curl -sf \
  "${GITEA_HOST_URL}/api/v1/repos/${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}/git/trees/main?recursive=false" \
  -u "${GITEA_ADMIN_USER}:${GITEA_ADMIN_PASS}" 2>/dev/null \
  | grep -o '"path"' | wc -l | tr -d ' ' || echo "0")

# If there are already 3+ tracked paths the repo is initialised.
if [ "${TREE_COUNT}" -ge 3 ] 2>/dev/null; then
  skip "gitops repo already has content (${TREE_COUNT} paths) — skipping init"
  echo ""
  exit 0
fi

echo ""

# ── Clone into a temp dir ─────────────────────────────────────────────────
TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}"' EXIT

info "Cloning gitops repo into temp dir..."

git -c advice.detachedHead=false clone --quiet "${CLONE_URL}" "${TMPDIR}/gitops"
ok "cloned to ${TMPDIR}/gitops"
echo ""

cd "${TMPDIR}/gitops"

# Configure git identity for the commit (local to this clone only).
git config user.email "suparship-dev@local"
git config user.name  "suparShip Dev Bot"

# ── Build the monorepo skeleton ───────────────────────────────────────────
info "Creating gitops repo skeleton..."

# 1. charts/ — copy Helm charts from the suparship templates dir.
mkdir -p charts
cp -r "${REPO_ROOT}/templates/web-service/chart" charts/web-service
ok "charts/web-service  (copied from templates/web-service/chart)"
if [ -d "${REPO_ROOT}/templates/color-app/chart" ]; then
  cp -r "${REPO_ROOT}/templates/color-app/chart" charts/color-app
  ok "charts/color-app    (copied from templates/color-app/chart)"
fi

# 2. gitops-output placeholder — suparship writes per-app dirs here.
mkdir -p gitops-output
touch gitops-output/.gitkeep
ok "gitops-output/.gitkeep"

# 3. gitops-output/_infra/ — cluster-wide infra manifests (ESO stores etc).
#    suparship writes ExternalSecret CRs here; the ClusterSecretStores are
#    applied directly by install-eso.sh and also tracked here for auditability.
mkdir -p gitops-output/_infra
cat > gitops-output/_infra/eso-stores.yaml <<'EOYAML'
# ClusterSecretStore definitions for the suparShip External Secrets Operator
# integration. Applied once during cluster bootstrap by hack/install-eso.sh.
#
# suparship-k8s-store  — demo backend; reads Secrets from suparship-system.
#
# To add Vault or AWS Secrets Manager stores, create additional
# ClusterSecretStore resources with a valid spec.provider section.
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: suparship-k8s-store
  labels:
    suparship.io/managed-by: suparship
  annotations:
    suparship.io/description: "Kubernetes Secrets backend for demo/default use. Reads Secrets from suparship-system namespace."
spec:
  provider:
    kubernetes:
      remoteNamespace: suparship-system
      auth:
        serviceAccount:
          name: suparship-eso-reader
          namespace: suparship-system
EOYAML
ok "gitops-output/_infra/eso-stores.yaml"

# 3. README.
cat > README.md <<'EOF'
# suparShip GitOps Repo

This repository is the GitOps source of truth for suparShip.

## Layout

```
charts/
  <template-name>/          Helm charts referenced by ArgoCD Applications.
                            Populated by: hack/init-gitops-repo.sh

gitops-output/
  _infra/
    eso-stores.yaml         ClusterSecretStore definitions for ESO backends.
                            Applied directly by hack/install-eso.sh; tracked
                            here for auditability.
    eso-secrets-*.yaml      ExternalSecret CRs for upper-level secret refs.
                            Committed by: suparship server on env config update.

  <project>/<app>/<env>/
    argocd-app.yaml         ArgoCD Application CRD for this app+env.
                            Committed by: suparship server on app create/update.
```

## How it works

1. `suparship` server commits `argocd-app.yaml` files under `gitops-output/`.
2. The root ArgoCD Application (`suparship-apps`) watches `gitops-output/`
   recursively for any `argocd-app.yaml` and applies them to the cluster.
3. Each child Application syncs the Helm chart from `charts/<template>/`
   with inline values specific to that environment.
4. Env vars are loaded from ConfigMaps via `envFrom` in hierarchy order:
   Org < Environment < Project < App < App-Environment.
5. Secrets are pulled by ESO from the configured ClusterSecretStore and
   injected into pods as Kubernetes Secrets (also via `envFrom`).

## Local dev

- Gitea UI: http://gitea.localhost:8880  (user: gitops)
- Source of credentials: `.env.cluster` (git-ignored)
EOF
ok "README.md"

echo ""

# ── Commit and push ───────────────────────────────────────────────────────
info "Committing and pushing..."

git add .
git commit --quiet -m "chore: initialise gitops monorepo skeleton

- charts/web-service copied from templates/web-service/chart
- gitops-output/_infra/eso-stores.yaml — ClusterSecretStore definitions
- gitops-output/ placeholder for suparship-generated manifests
- README documenting the layout and workflow"

git push --quiet origin main
ok "pushed to ${GITOPS_REPO_HOST_URL}"
echo ""
