#!/usr/bin/env bash
# hack/init-gitops-repo.sh — bootstrap the gitops monorepo content in Gitea.
#
# Pushes the initial directory structure that suparship writes to and ArgoCD
# syncs from. Safe to re-run: checks for existing content before pushing.
#
# Monorepo layout after this script:
#
#   charts/
#     web-service/          ← Helm chart, copied from templates/web-service/chart/
#       Chart.yaml
#       values.yaml
#       templates/
#   gitops-output/
#     .gitkeep              ← placeholder; suparship writes per-app dirs here
#   README.md
#
# ArgoCD infra manifests (ApplicationSets, AppProjects) are committed by
# suparship to:
#   gitops-output/_infra/{env}-appset.yaml
#   gitops-output/_infra/{project}-appproject.yaml
#
# Per-app Git File generator parameters are committed to:
#   gitops-output/{env}/{project}/{app}/app.yaml
#   gitops-output/{env}/{project}/{app}/values.yaml
#
# The root ArgoCD App of Apps (suparship-apps) watches:
#   gitops-output/_infra/**/*.yaml
#
# Environment variables (all required — set by install-gitea.sh):
#   GITEA_HOST_URL       e.g. http://gitea.localhost:8880
#   GITEA_ADMIN_USER     e.g. gitops
#   GITEA_ADMIN_PASS     e.g. gitops-dev-only
#   GITOPS_REPO_ORG      e.g. gitops
#   GITOPS_REPO_NAME     e.g. gitops
#   GITEA_CLUSTER_URL    e.g. http://gitea-http.gitea.svc.cluster.local:3000
#   REPO_ROOT            absolute path to the suparship repo root
#
# Used by: hack/install-gitea.sh
set -euo pipefail

# ── Helpers ───────────────────────────────────────────────────────────────
info()  { printf "  \033[0;36m%s\033[0m\n" "$*"; }
ok()    { printf "  \033[0;32m✓\033[0m  %s\n" "$*"; }
skip()  { printf "  \033[0;33m–\033[0m  %s\n" "$*"; }
die()   { printf "  \033[0;31mERROR:\033[0m %s\n" "$*" >&2; exit 1; }

# ── Validate required env vars ────────────────────────────────────────────
: "${GITEA_HOST_URL:?GITEA_HOST_URL is required}"
: "${GITEA_ADMIN_USER:?GITEA_ADMIN_USER is required}"
: "${GITEA_ADMIN_PASS:?GITEA_ADMIN_PASS is required}"
: "${GITOPS_REPO_ORG:?GITOPS_REPO_ORG is required}"
: "${GITOPS_REPO_NAME:?GITOPS_REPO_NAME is required}"
: "${GITEA_CLUSTER_URL:?GITEA_CLUSTER_URL is required}"
: "${REPO_ROOT:?REPO_ROOT is required}"

GITOPS_REPO_HOST_URL="${GITEA_HOST_URL}/${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}.git"
# Credentials embedded in URL so git never prompts interactively.
CLONE_URL="http://${GITEA_ADMIN_USER}:${GITEA_ADMIN_PASS}@${GITEA_HOST_URL#http://}/${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}.git"

# ── Wait for Gitea to be reachable ───────────────────────────────────────
info "Waiting for Gitea at ${GITEA_HOST_URL} ..."
READY=false
for i in $(seq 1 20); do
  if curl -sf --max-time 3 "${GITEA_HOST_URL}/api/v1/version" >/dev/null 2>&1; then
    READY=true
    break
  fi
  printf "."
  sleep 3
done
echo ""
if [ "${READY}" = "false" ]; then
  die "Gitea did not become reachable at ${GITEA_HOST_URL} within 60s."
fi
ok "Gitea is reachable"
echo ""

# ── Ensure the gitops repo exists ────────────────────────────────────────
info "Ensuring gitops repo '${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}' exists..."

REPO_STATUS=$(curl -sf \
  "${GITEA_HOST_URL}/api/v1/repos/${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}" \
  -u "${GITEA_ADMIN_USER}:${GITEA_ADMIN_PASS}" \
  -o /dev/null -w "%{http_code}" 2>/dev/null || echo "000")

if [ "${REPO_STATUS}" = "200" ]; then
  skip "repo already exists"
else
  info "Repo not found (HTTP ${REPO_STATUS}) — creating via Gitea API..."
  CREATE_STATUS=$(curl -sf -X POST \
    "${GITEA_HOST_URL}/api/v1/user/repos" \
    -H "Content-Type: application/json" \
    -u "${GITEA_ADMIN_USER}:${GITEA_ADMIN_PASS}" \
    -d "{
      \"name\": \"${GITOPS_REPO_NAME}\",
      \"description\": \"suparship GitOps manifests — generated by suparship\",
      \"private\": false,
      \"auto_init\": true,
      \"default_branch\": \"main\"
    }" \
    -o /dev/null -w "%{http_code}" 2>/dev/null || echo "000")
  if [ "${CREATE_STATUS}" = "201" ]; then
    ok "repo created"
  else
    die "Failed to create repo (HTTP ${CREATE_STATUS}). Is the Gitea user '${GITEA_ADMIN_USER}' correct?"
  fi
fi
echo ""

# ── Check if already initialised ─────────────────────────────────────────
info "Checking if gitops repo already has content..."

TREE_COUNT=$(curl -sf \
  "${GITEA_HOST_URL}/api/v1/repos/${GITOPS_REPO_ORG}/${GITOPS_REPO_NAME}/git/trees/main?recursive=false" \
  -u "${GITEA_ADMIN_USER}:${GITEA_ADMIN_PASS}" 2>/dev/null \
  | grep -o '"path"' | wc -l | tr -d ' ' || echo "0")

# If there are already 3+ tracked paths the repo is initialised.
if [ "${TREE_COUNT}" -ge 3 ] 2>/dev/null; then
  skip "gitops repo already has content (${TREE_COUNT} paths) — skipping init"
  echo ""
  exit 0
fi

echo ""

# ── Clone into a temp dir ─────────────────────────────────────────────────
TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}"' EXIT

info "Cloning gitops repo into temp dir..."

git -c advice.detachedHead=false clone --quiet "${CLONE_URL}" "${TMPDIR}/gitops"
ok "cloned to ${TMPDIR}/gitops"
echo ""

cd "${TMPDIR}/gitops"

# Configure git identity for the commit (local to this clone only).
git config user.email "suparship-dev@local"
git config user.name  "suparship Dev Bot"

# ── Build the monorepo skeleton ───────────────────────────────────────────
info "Creating gitops repo skeleton..."

# 1. charts/ — copy Helm charts from the suparship templates dir.
mkdir -p charts
cp -r "${REPO_ROOT}/templates/web-service/chart" charts/web-service
ok "charts/web-service  (copied from templates/web-service/chart)"
if [ -d "${REPO_ROOT}/templates/color-app/chart" ]; then
  cp -r "${REPO_ROOT}/templates/color-app/chart" charts/color-app
  ok "charts/color-app    (copied from templates/color-app/chart)"
fi

# 2. gitops-output placeholder — suparship writes per-app dirs here.
mkdir -p gitops-output
touch gitops-output/.gitkeep
ok "gitops-output/.gitkeep"

# 3. gitops-output/_infra/ — cluster-wide infra manifests.
#    ClusterSecretStores are now generated by the suparship publisher from
#    VaultBinding configuration. The init script only creates the directory.
mkdir -p gitops-output/_infra/secret-stores
touch gitops-output/_infra/secret-stores/.gitkeep
ok "gitops-output/_infra/secret-stores/.gitkeep"

# 3. README.
cat > README.md <<'EOF'
# suparship GitOps Repo

This repository is the GitOps source of truth for suparship.

## Layout

```
charts/
  <template-name>/          Helm charts referenced by ArgoCD Applications.
                            Populated by: hack/init-gitops-repo.sh

gitops-output/
  _infra/
    <env>-appset.yaml       ArgoCD ApplicationSet for one environment cluster.
                            Git File generator watches <env>/*/*/app.yaml.
                            Committed by: suparship server on app create/update.
    <project>-appproject.yaml  ArgoCD AppProject scoping an environment.
                            Committed by: suparship server.
    previews-appset.yaml    ArgoCD ApplicationSet for all preview environments.
    eso-stores.yaml         ClusterSecretStore definitions for ESO backends.
                            (Legacy; new installs use _infra/secret-stores/)
    secrets-<env>-app.yaml  ArgoCD Application that syncs secret-stores/<env>/
                            to the target cluster. Discovered by root app.
    secret-stores/
      <env>/
        sealed-token.yaml   SealedSecret with encrypted Connect token.
        store.yaml          ClusterSecretStore referencing the sealed token.
                            Only synced by the per-env secrets-<env>-app.yaml.
    kargo/
      <project>-project.yaml          Kargo Project CR.
      <project>-<app>-warehouse.yaml  Kargo Warehouse CR.
      <project>-<app>-<env>-stage.yaml  Kargo Stage CR per stable env.

  <env>/<project>/<app>/
    app.yaml                Git File generator parameters (name, project,
                            template, …). Consumed by the <env>-appset.yaml
                            ApplicationSet to generate an ArgoCD Application.
    values.yaml             Helm values for this app+env pair.
                            Referenced by the ApplicationSet chart source.
```

## How it works

1. `suparship` server commits `_infra/*-appset.yaml` and `_infra/*-appproject.yaml`
   for each project's environments.
2. The root ArgoCD Application (`suparship-apps`) watches `gitops-output/_infra/*.yaml`
   and `gitops-output/_infra/kargo/*.yaml`. It applies ApplicationSets, AppProjects,
   Kargo CRs, and per-env secrets Application manifests to the cluster.
   Note: `_infra/secret-stores/` subdirectories are NOT directly synced by the
   root app — they are synced by the per-env `secrets-<env>-app.yaml` child Application.
3. Each ApplicationSet uses a Git File generator to discover `app.yaml` files
   under `gitops-output/<env>/<project>/<app>/app.yaml` and generates one
   ArgoCD Application per file.
4. Each generated Application syncs the Helm chart from `charts/<template>/`
   with environment-specific values from the matching `values.yaml`.
4. Env vars are loaded from ConfigMaps via `envFrom` in hierarchy order:
   Org < Environment < Project < App < App-Environment.
5. Secrets are pulled by ESO from the configured ClusterSecretStore(s)
   (generated from VaultBindings — see docs/secrets.md) and injected
   into pods as Kubernetes Secrets (also via `envFrom`).

## Local dev

- Gitea UI: http://gitea.localhost:8880  (user: gitops)
- Source of credentials: `.env.cluster` (git-ignored)
EOF
ok "README.md"

echo ""

# ── Commit and push ───────────────────────────────────────────────────────
info "Committing and pushing..."

git add .
git commit --quiet -m "chore: initialise gitops monorepo skeleton

- charts/web-service copied from templates/web-service/chart
- gitops-output/_infra/secret-stores/ placeholder for ClusterSecretStore YAML
- gitops-output/ placeholder for suparship-generated manifests
- README documenting the layout and workflow"

git push --quiet origin main
ok "pushed to ${GITOPS_REPO_HOST_URL}"
echo ""
