#!/usr/bin/env bash
# hack/seed.sh — apply deterministic demo data to the suparship cluster.
#
# Creates (or updates) three ConfigMaps in the suparship-system namespace:
#   suparship-org-config      — default org (admins team, org_admin binding)
#   suparship-project-demo    — demo project (hello service, staging + prod)
#
# Idempotent: uses kubectl apply, safe to run multiple times.
# The seeded data mirrors internal/fake/seed.go so the UI looks consistent
# across fake mode (task dev) and cluster mode (task up).
#
# Prerequisites:
#   task up   # cluster and suparship-system namespace must exist
#
# Admin credentials are NOT created here — they require a bcrypt hash.
# Run once per cluster:
#   ./bin/suparship admin bootstrap
#
# Usage:
#   ./hack/seed.sh       # run directly
#   task seed            # preferred: via Taskfile
set -euo pipefail

NAMESPACE="suparship-system"
SEED_DIR="config/seed"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# ── Helpers ───────────────────────────────────────────────────────────────
ok()  { printf "  \033[0;32m✓\033[0m  %s\n" "$*"; }
die() { printf "  \033[0;31mERROR:\033[0m %s\n" "$*" >&2; exit 1; }

# ── Prereqs ───────────────────────────────────────────────────────────────
command -v kubectl >/dev/null 2>&1 || die "'kubectl' not found."
# Pin kubectl to the dev cluster — see hack/dev/lib.sh.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/dev/lib.sh"
require_dev_context
kubectl get namespace "$NAMESPACE" >/dev/null 2>&1 \
  || die "Namespace '$NAMESPACE' not found. Run: task up"

echo ""
echo "  suparship — seed demo data  (kubectl apply -f ${SEED_DIR}/)"
echo "  ──────────────────────────────────────────────────────────────────"
echo ""

# ── Apply all seed manifests ──────────────────────────────────────────────
# In multi-cluster mode the placeholder cluster records in clusters.yaml are not
# just unrealistic, they are actively harmful: both point at
# https://kubernetes.default.svc, and any app published while an environment is
# bound to one leaves a dead envs/<env>/<project>/<app>/_targets/<placeholder>/
# entry that generates an ArgoCD Application aimed at the tooling cluster. Some
# seeded apps are embedded in the project record rather than being first-class
# apps, so they are not reachable via the sync API and that entry never gets
# rewritten.
#
# Skipping them leaves the environments referring to clusters that do not exist,
# which the publisher treats as unbound and skips — so nothing is published until
# hack/dev/seed-multi.sh binds the environments to the REAL clusters.
if [ "${SUPARSHIP_MULTI:-}" = "1" ]; then
  for f in "${SEED_DIR}"/*.yaml; do
    case "$(basename "$f")" in
      clusters.yaml) continue ;;
    esac
    kubectl apply -f "$f" --namespace="${NAMESPACE}" >/dev/null
  done
  ok "skipped clusters.yaml (multi-cluster mode — real clusters register later)"
else
  kubectl apply -f "${SEED_DIR}/" --namespace="${NAMESPACE}" >/dev/null
fi

ok "suparship-org-config          (default org, admins team)"
ok "suparship-project-demo        (hello service, staging + prod)"

# ── Create ArgoCD AppProject for the demo project ─────────────────────────
# Each suparship project needs a matching ArgoCD AppProject so that Application
# CRDs generated by suparship (spec.project: demo) are accepted by ArgoCD.
# The publisher will write appproject.yaml to the gitops repo on app create/sync,
# but we also create it imperatively here so the cluster is ready immediately
# without waiting for a gitops push + ArgoCD sync cycle.
if kubectl get namespace argocd >/dev/null 2>&1; then
  kubectl apply -f - >/dev/null <<'APPPROJECT'
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    suparship.io/managed-by: suparship
spec:
  description: suparship demo project
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
APPPROJECT
  ok "argocd AppProject 'demo'  (created/updated in argocd namespace)"
else
  printf "  \033[0;33m!\033[0m  argocd namespace not found — skipping AppProject creation.\n"
  printf "      Run 'task up' first if you need GitOps integration.\n"
fi

# ── Admin credentials reminder ────────────────────────────────────────────
echo ""
if kubectl get secret suparship-admin-auth -n "$NAMESPACE" >/dev/null 2>&1; then
  ok "suparship-admin-auth          (already exists)"
else
  printf "  \033[0;33m!\033[0m  No admin credentials found.\n"
  printf "      Build and run once per cluster:\n"
  printf "        go build -o bin/suparship ./cmd/suparship\n"
  printf "        ./bin/suparship admin bootstrap\n"
fi

cat <<EOF

  ──────────────────────────────────────────────────────────────────
  Seed complete.

  Verify:
    kubectl get configmaps -n ${NAMESPACE} -l suparship.io/type=project
    kubectl get configmaps -n ${NAMESPACE} -l suparship.io/type=preview

EOF
