#!/usr/bin/env bash
# hack/write-dev-credentials.sh — write or update a key=value pair in .env.cluster.
#
# .env.cluster is a git-ignored file that stores auto-generated dev cluster
# credentials (ArgoCD password, Gitea password, gitops repo URLs). It is
# written by the dev-cluster scripts and can be sourced in a
# shell to populate the environment for manual cluster operations.
#
# Usage — source and call the function from another script:
#   source hack/write-dev-credentials.sh
#   write_credential ARGOCD_PASSWORD "abc123"
#
# Usage — run directly from the shell:
#   ./hack/write-dev-credentials.sh ARGOCD_PASSWORD "abc123"

CREDS_FILE="${CREDS_FILE:-$(cd "$(dirname "$0")/.." && pwd)/.env.cluster}"

# ── write_credential KEY VALUE ────────────────────────────────────────────
# Creates .env.cluster if absent (with a safety header), then sets or
# updates the line  KEY=VALUE  in the file.
write_credential() {
  local key="$1"
  local val="$2"

  if [ ! -f "${CREDS_FILE}" ]; then
    cat > "${CREDS_FILE}" <<'EOF'
# suparship cluster dev credentials — NOT tracked in git.
#
# Auto-generated by: the suparship dev-cluster scripts
# Regenerate by re-running:  task dev:cluster
#
# Source in your shell for manual cluster operations:
#   source .env.cluster
#
# WARNING: contains plaintext dev passwords — local dev only.
EOF
  fi

  if grep -q "^${key}=" "${CREDS_FILE}" 2>/dev/null; then
    # Replace existing value in-place (macOS-compatible: temp backup + remove).
    sed -i.bak "s|^${key}=.*|${key}=${val}|" "${CREDS_FILE}"
    rm -f "${CREDS_FILE}.bak"
  else
    printf "%s=%s\n" "${key}" "${val}" >> "${CREDS_FILE}"
  fi
}

# ── Direct invocation: ./hack/write-dev-credentials.sh KEY VALUE ─────────
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  if [ $# -ne 2 ]; then
    echo "Usage: $0 KEY VALUE" >&2
    exit 1
  fi
  write_credential "$1" "$2"
fi
