apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: voiceai

images:
  - name: acrsharedsouthcentralusbiglysales.azurecr.io/biglysales-voiceai-livekit
    newTag: "44ac5fe"

commonLabels:
  environment: staging

patches:
- path: patch-livekit-agent.yaml
- path: patch-livekit-worker.yaml