{{- if .Values.autoscaling.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "web-service.fullname" . }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ include "web-service.fullname" . }}
  minReplicaCount: {{ .Values.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicaCount }}
  {{- with .Values.autoscaling.cooldownPeriod }}
  cooldownPeriod: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.pollingInterval }}
  pollingInterval: {{ . }}
  {{- end }}
  triggers:
    {{- if .Values.autoscaling.triggers }}
    {{- toYaml .Values.autoscaling.triggers | nindent 4 }}
    {{- else }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: {{ .Values.autoscaling.cpuTarget | quote }}
    - type: memory
      metricType: Utilization
      metadata:
        value: {{ .Values.autoscaling.memoryTarget | quote }}
    {{- end }}
  {{- with .Values.autoscaling.behavior }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
