package gitops

// AppSetEnv parameterises one environment in an ApplicationSet.
// Each instance maps to one cluster in the env/cluster-centric Model B layout.
type AppSetEnv struct {
	// EnvName is the logical environment name, e.g. "staging".
	EnvName string
	// ClusterServer is the Kubernetes API server URL for this environment's cluster.
	// Written as spec.destination.server in generated Applications.
	ClusterServer string
	// BaseDomain is the ingress base domain for apps in this environment,
	// e.g. "staging.acme.com". Used in values.yaml generation, not in the AppSet itself.
	BaseDomain string
}

// AppSetOptions carries shared configuration for all ApplicationSet builders.
type AppSetOptions struct {
	// ArgoCDNamespace is the namespace where ApplicationSet objects are created.
	// Defaults to "argocd".
	ArgoCDNamespace string
	// TargetRevision is the Git ref ApplicationSets deploy. Defaults to "HEAD".
	TargetRevision string
	// SyncAutomated enables automated sync with prune and selfHeal on generated Applications.
	SyncAutomated bool
	// SubPath mirrors PublisherConfig.SubPath so the ApplicationSet's
	// Git File generator path glob and per-app source.path point at the
	// same directories the publisher writes to. Empty (default) = repo
	// root.
	SubPath string
}

// ApplicationSet is a minimal, serializable representation of an ArgoCD
// ApplicationSet CRD. Only the fields required for suparShip's env/cluster-centric
// model are included.
type ApplicationSet struct {
	APIVersion string             `yaml:"apiVersion"`
	Kind       string             `yaml:"kind"`
	Metadata   ObjectMeta         `yaml:"metadata"`
	Spec       ApplicationSetSpec `yaml:"spec"`
}

// ApplicationSetSpec is the spec section of an ArgoCD ApplicationSet.
type ApplicationSetSpec struct {
	Generators []ApplicationSetGenerator `yaml:"generators"`
	Template   ApplicationSetTemplate    `yaml:"template"`
}

// ApplicationSetGenerator holds one generator configuration.
// Only the Git File generator is used in suparShip's model.
type ApplicationSetGenerator struct {
	// Git is the Git File generator configuration.
	Git *GitFileGenerator `yaml:"git,omitempty"`
}

// GitFileGenerator discovers parameterisation files in a Git repository.
// Note: the ApplicationSet git generator uses "revision" (not "targetRevision"
// which is used in Application source specs). Using the wrong field name causes
// ArgoCD to reject the ApplicationSet with "revision: Required value".
type GitFileGenerator struct {
	RepoURL  string            `yaml:"repoURL"`
	Revision string            `yaml:"revision"`
	Files    []GitFilePathSpec `yaml:"files"`
}

// GitFilePathSpec is one path glob for the Git File generator.
type GitFilePathSpec struct {
	Path string `yaml:"path"`
}

// ApplicationSetTemplate is the Application template inside an ApplicationSet.
type ApplicationSetTemplate struct {
	Metadata ObjectMeta              `yaml:"metadata"`
	Spec     ApplicationSetAppSpec   `yaml:"spec"`
}

// ApplicationSetAppSpec is the spec of Applications generated by the AppSet.
// It uses multi-source Applications (ArgoCD ≥ v2.6).
type ApplicationSetAppSpec struct {
	Project     string                      `yaml:"project"`
	Sources     []ApplicationSource         `yaml:"sources"`
	Destination ApplicationDestination      `yaml:"destination"`
	SyncPolicy  *SyncPolicy                 `yaml:"syncPolicy,omitempty"`
}

// BuildArgoAppSet generates the per-cluster stable-environment ApplicationSet
// for one environment directory (Model B layout).
//
// The generated ApplicationSet:
//   - Uses a Git File generator that discovers all app.yaml files under
//     "gitops-output/{envName}/*/*/app.yaml" to enumerate apps.
//   - Creates multi-source Applications: one source is the Helm chart at
//     "charts/{{template}}", the other is a ref source pointing at the
//     per-app values directory for "$appvalues/values.yaml".
//   - Hardcodes spec.destination.server to env.ClusterServer (constant per AppSet).
//   - Uses "{{namespace}}" as spec.destination.namespace — the resolved
//     namespace is written into each app's app.yaml at publish time, so each
//     app can have a different namespace within the same ApplicationSet.
//
// BuildArgoAppSet is a pure function — identical inputs produce identical output.
func BuildArgoAppSet(env AppSetEnv, repoURL string, opts AppSetOptions) *ApplicationSet {
	if opts.ArgoCDNamespace == "" {
		opts.ArgoCDNamespace = defaultArgoCDNS
	}
	if opts.TargetRevision == "" {
		opts.TargetRevision = defaultTargetRevision
	}
	if env.ClusterServer == "" {
		env.ClusterServer = defaultDestination
	}

	// Source 1: values ref — checks out the ENTIRE gitops repo so $appvalues
	// resolves to the repo root. No `path` is set intentionally: when `path` is
	// set, ArgoCD 2.13 erroneously resolves $ref to the repo root anyway, so we
	// make the intent explicit and use the full path in source 2's valueFiles.
	valuesRefSource := ApplicationSource{
		RepoURL:        repoURL,
		TargetRevision: opts.TargetRevision,
		Ref:            "appvalues",
	}

	// Source 2: Helm chart; reads per-app values from the repo via $appvalues.
	// The full path is used because $appvalues resolves to the repo root (see above).
	valuesFilePath := "$appvalues/" + joinSubPath(opts.SubPath, "envs", env.EnvName, "{{project}}", "{{name}}", "values.yaml")
	chartSource := ApplicationSource{
		RepoURL:        repoURL,
		Path:           joinSubPath(opts.SubPath, "charts", "{{template}}"),
		TargetRevision: opts.TargetRevision,
		Helm: &HelmSource{
			ReleaseName: "{{name}}",
			ValueFiles:  []string{valuesFilePath},
		},
	}

	// Source 3: per-app platform manifests (env-configmap, external-secret,
	// env-configmap, external-secret). Without this, those files are
	// written to gitops but never reach the cluster — the chart's
	// envFrom is `optional: true` so it silently degrades. Include
	// filter skips app.yaml + values.yaml, which are parameter/values
	// files for the ApplicationSet, not Kubernetes manifests.
	//
	// Plain-manifest mode (no kustomize): we tried bundling the per-app
	// manifests via kustomization.yaml, but ArgoCD's `directory:` source
	// treats files in `Include` as raw manifests — it shipped the
	// kustomization.yaml to the API server as a Kustomization CRD,
	// which doesn't exist on workload clusters and broke sync. The
	// include filter alone is sufficient.
	//
	// Extension story: operators wanting to add manifests beyond what
	// suparship models should layer a separate ArgoCD Application that
	// overlays this one, NOT edit files in this directory (the
	// publisher regenerates them every publish).
	platformManifestsSource := ApplicationSource{
		RepoURL:        repoURL,
		Path:           joinSubPath(opts.SubPath, "envs", env.EnvName, "{{project}}", "{{name}}"),
		TargetRevision: opts.TargetRevision,
		Directory: &DirectorySource{
			Recurse: false,
			// Plain-manifest mode: list each file ArgoCD should apply.
			// Do NOT include kustomization.yaml here — directory mode
			// treats listed files as raw manifests, so a kustomization
			// would be shipped to the API server as a Kustomization CRD
			// (which doesn't exist, breaking sync).
			Include: "{env-configmap.yaml,external-secret.yaml}",
		},
	}

	var syncPolicy *SyncPolicy
	if opts.SyncAutomated {
		syncPolicy = &SyncPolicy{
			Automated:   &AutomatedSyncPolicy{Prune: true, SelfHeal: true},
			SyncOptions: []string{"CreateNamespace=true"},
		}
	} else {
		// Always create the destination namespace even without auto-sync so
		// ArgoCD can deploy into the correct namespace on the first manual sync.
		syncPolicy = &SyncPolicy{
			SyncOptions: []string{"CreateNamespace=true"},
		}
	}

	return &ApplicationSet{
		APIVersion: argoAppSetAPIVersion,
		Kind:       "ApplicationSet",
		Metadata: ObjectMeta{
			Name:      env.EnvName,
			Namespace: opts.ArgoCDNamespace,
			Annotations: map[string]string{
				syncWaveAnnotation: "0",
			},
		},
		Spec: ApplicationSetSpec{
		Generators: []ApplicationSetGenerator{
			{
				Git: &GitFileGenerator{
					RepoURL:  repoURL,
					Revision: opts.TargetRevision,
					Files: []GitFilePathSpec{
						{Path: joinSubPath(opts.SubPath, "envs", env.EnvName, "*", "*", "app.yaml")},
					},
				},
			},
		},
		Template: ApplicationSetTemplate{
			Metadata: ObjectMeta{
				// Application name MUST mirror gitops.ApplicationName —
				// {project}-{app}-{env} — so two suparship projects can
				// each have an app called e.g. "color-app" without
				// producing duplicate Application names that break the
				// ApplicationSet reconciler.
				Name:      "{{project}}-{{name}}-" + env.EnvName,
				Namespace: opts.ArgoCDNamespace,
				Labels: map[string]string{
					labelApp:     "{{name}}",
					labelProject: "{{project}}",
					labelEnv:     env.EnvName,
				},
				// Authorize the corresponding Kargo Stage to trigger ArgoCD syncs
				// for this Application. The annotation value is "<namespace>:<stage>"
				// where namespace = Kargo project namespace = suparship project name,
				// and stage = "{app}-{env}" per KargoStageName convention.
				Annotations: map[string]string{
					"kargo.akuity.io/authorized-stage": "{{project}}:{{name}}-" + env.EnvName,
				},
			},
			Spec: ApplicationSetAppSpec{
				Project:     "{{project}}",
				Sources:     []ApplicationSource{valuesRefSource, chartSource, platformManifestsSource},
				Destination: ApplicationDestination{Server: env.ClusterServer, Namespace: "{{namespace}}"},
				SyncPolicy:  syncPolicy,
			},
		},
		},
	}
}

// BuildArgoExternalAppSet generates the per-cluster ApplicationSet for
// external-mode apps — those whose template's engine.chart references a
// Helm registry rather than a chart bundled in the gitops repo.
//
// Differences from BuildArgoAppSet:
//
//   - The chart source uses source.repoURL + source.chart + source.targetRevision
//     to point at the Helm registry, instead of source.path pointing at
//     a charts/ directory in the gitops repo. ArgoCD's repo-server pulls
//     fresh from the registry; chart bytes never land in the gitops repo.
//
//   - The Git File generator's path glob is envs-external/{env}/{project}/{app}/
//     so this AppSet picks up only external-mode apps. The publisher
//     writes external-mode app.yaml files to that path and inline-mode
//     ones to envs/{env}/... — no overlap, so each app belongs to
//     exactly one AppSet without needing parameter selectors.
//
//   - Per-app platform manifests (env-configmap, external-secret) are
//     still written in the same env-relative directory, so the
//     directory source includes them the same way as inline-mode apps.
//
// Pure function — identical inputs produce identical output.
func BuildArgoExternalAppSet(env AppSetEnv, repoURL string, opts AppSetOptions) *ApplicationSet {
	if opts.ArgoCDNamespace == "" {
		opts.ArgoCDNamespace = defaultArgoCDNS
	}
	if opts.TargetRevision == "" {
		opts.TargetRevision = defaultTargetRevision
	}
	if env.ClusterServer == "" {
		env.ClusterServer = defaultDestination
	}

	// Source 1: values ref — same shape as inline-mode AppSet. Lets the
	// chart source overlay $appvalues onto the env-specific values.yaml.
	valuesRefSource := ApplicationSource{
		RepoURL:        repoURL,
		TargetRevision: opts.TargetRevision,
		Ref:            "appvalues",
	}

	// Source 2: chart from the Helm registry, parameterised per app.
	// chartRepoURL/chartName/chartVersion come from the per-app app.yaml
	// (AppMetadata.ChartRepoURL etc.) which the Git File generator
	// flattens into template parameters.
	valuesFilePath := "$appvalues/" + joinSubPath(opts.SubPath, "envs-external", env.EnvName, "{{project}}", "{{name}}", "values.yaml")
	chartSource := ApplicationSource{
		RepoURL:        "{{chartRepoURL}}",
		Chart:          "{{chartName}}",
		TargetRevision: "{{chartVersion}}",
		Helm: &HelmSource{
			ReleaseName: "{{name}}",
			ValueFiles:  []string{valuesFilePath},
		},
	}

	// Source 3: per-app platform manifests, same as inline-mode AppSet.
	platformManifestsSource := ApplicationSource{
		RepoURL:        repoURL,
		Path:           joinSubPath(opts.SubPath, "envs-external", env.EnvName, "{{project}}", "{{name}}"),
		TargetRevision: opts.TargetRevision,
		Directory: &DirectorySource{
			Recurse: false,
			Include: "{env-configmap.yaml,external-secret.yaml}",
		},
	}

	var syncPolicy *SyncPolicy
	if opts.SyncAutomated {
		syncPolicy = &SyncPolicy{
			Automated:   &AutomatedSyncPolicy{Prune: true, SelfHeal: true},
			SyncOptions: []string{"CreateNamespace=true"},
		}
	} else {
		syncPolicy = &SyncPolicy{
			SyncOptions: []string{"CreateNamespace=true"},
		}
	}

	return &ApplicationSet{
		APIVersion: argoAppSetAPIVersion,
		Kind:       "ApplicationSet",
		Metadata: ObjectMeta{
			// Distinct name from the inline AppSet so both can coexist
			// in the argocd namespace targeting the same env.
			Name:      env.EnvName + "-external",
			Namespace: opts.ArgoCDNamespace,
			Annotations: map[string]string{
				syncWaveAnnotation: "0",
			},
		},
		Spec: ApplicationSetSpec{
			Generators: []ApplicationSetGenerator{
				{
					Git: &GitFileGenerator{
						RepoURL:  repoURL,
						Revision: opts.TargetRevision,
						Files: []GitFilePathSpec{
							{Path: joinSubPath(opts.SubPath, "envs-external", env.EnvName, "*", "*", "app.yaml")},
						},
					},
				},
			},
			Template: ApplicationSetTemplate{
				Metadata: ObjectMeta{
					Name:      "{{project}}-{{name}}-" + env.EnvName,
					Namespace: opts.ArgoCDNamespace,
					Labels: map[string]string{
						labelApp:     "{{name}}",
						labelProject: "{{project}}",
						labelEnv:     env.EnvName,
					},
					Annotations: map[string]string{
						"kargo.akuity.io/authorized-stage": "{{project}}:{{name}}-" + env.EnvName,
					},
				},
				Spec: ApplicationSetAppSpec{
					Project:     "{{project}}",
					Sources:     []ApplicationSource{valuesRefSource, chartSource, platformManifestsSource},
					Destination: ApplicationDestination{Server: env.ClusterServer, Namespace: "{{namespace}}"},
					SyncPolicy:  syncPolicy,
				},
			},
		},
	}
}

// BuildArgoPreviewAppSet generates the previews ApplicationSet for a GitOps repo.
//
// The generated ApplicationSet:
//   - Uses a Git File generator on "gitops-output/previews/{project}/*/app.yaml".
//   - Each preview's app.yaml must contain: name, project, template, clusterServer, namespace.
//   - The destination.server and namespace come directly from the app.yaml parameters,
//     allowing previews to target any registered cluster.
//
// BuildArgoPreviewAppSet is a pure function — identical inputs produce identical output.
func BuildArgoPreviewAppSet(repoURL string, opts AppSetOptions) *ApplicationSet {
	if opts.ArgoCDNamespace == "" {
		opts.ArgoCDNamespace = defaultArgoCDNS
	}
	if opts.TargetRevision == "" {
		opts.TargetRevision = defaultTargetRevision
	}

	valuesRefSource := ApplicationSource{
		RepoURL:        repoURL,
		TargetRevision: opts.TargetRevision,
		Ref:            "previewvalues",
	}

	chartSource := ApplicationSource{
		RepoURL:        repoURL,
		Path:           joinSubPath(opts.SubPath, "charts", "{{template}}"),
		TargetRevision: opts.TargetRevision,
		Helm: &HelmSource{
			ReleaseName: "{{appName}}",
			ValueFiles:  []string{"$previewvalues/" + joinSubPath(opts.SubPath, "previews", "{{project}}", "{{name}}", "values.yaml")},
		},
	}

	var syncPolicy *SyncPolicy
	if opts.SyncAutomated {
		syncPolicy = &SyncPolicy{
			Automated:   &AutomatedSyncPolicy{Prune: true, SelfHeal: true},
			SyncOptions: []string{"CreateNamespace=true"},
		}
	} else {
		syncPolicy = &SyncPolicy{
			SyncOptions: []string{"CreateNamespace=true"},
		}
	}

	return &ApplicationSet{
		APIVersion: argoAppSetAPIVersion,
		Kind:       "ApplicationSet",
		Metadata: ObjectMeta{
			Name:      "previews",
			Namespace: opts.ArgoCDNamespace,
			Annotations: map[string]string{
				syncWaveAnnotation: "0",
			},
		},
		Spec: ApplicationSetSpec{
		Generators: []ApplicationSetGenerator{
			{
				Git: &GitFileGenerator{
					RepoURL:  repoURL,
					Revision: opts.TargetRevision,
					Files: []GitFilePathSpec{
						{Path: joinSubPath(opts.SubPath, "previews", "*", "*", "app.yaml")},
					},
				},
			},
		},
			Template: ApplicationSetTemplate{
				Metadata: ObjectMeta{
					Name:      "{{appName}}-{{previewName}}",
					Namespace: opts.ArgoCDNamespace,
					Labels: map[string]string{
						labelApp:     "{{appName}}",
						labelProject: "{{project}}",
						labelEnv:     "{{previewName}}",
						labelEnvType: string(previewEnvType),
					},
				},
				Spec: ApplicationSetAppSpec{
					Project: "{{project}}",
					Sources: []ApplicationSource{valuesRefSource, chartSource},
					// clusterServer and namespace come from the preview's app.yaml.
					Destination: ApplicationDestination{
						Server:    "{{clusterServer}}",
						Namespace: "{{namespace}}",
					},
					SyncPolicy: syncPolicy,
				},
			},
		},
	}
}

// AppMetadata is written as app.yaml for each app in each env directory.
// The Git File generator reads these fields as template parameters.
//
// Two chart-source modes are routed via the optional ChartType /
// ChartRepoURL / ChartName / ChartVersion fields:
//
//   - Inline mode (today's behaviour): ChartType is "inline" or empty.
//     The chart lives at charts/{template}/ in the gitops repo; the
//     existing ApplicationSet (BuildArgoAppSet) renders an Application
//     whose source.path points there.
//   - External mode: ChartType is "external" with the chart fields
//     populated. The chart lives in a Helm registry, never in the
//     gitops repo; the parallel ApplicationSet (BuildArgoExternalAppSet)
//     renders a multi-source Application with source.repoURL +
//     source.chart + source.targetRevision pointing at the registry.
//
// Each ApplicationSet's generator filters on chartType so an app's
// app.yaml is consumed by exactly one AppSet.
type AppMetadata struct {
	Name      string `yaml:"name"`
	Project   string `yaml:"project"`
	Template  string `yaml:"template"`
	// Namespace is the resolved Kubernetes namespace for this app+env instance.
	// Resolved at publish time by ResolveNamespace so each app can have a
	// different namespace even within the same ApplicationSet.
	Namespace string `yaml:"namespace"`

	// ChartType selects the chart-source flavour: "inline" (default,
	// omitted) or "external". Drives which ApplicationSet picks up this
	// app's app.yaml via generator selectors.
	ChartType string `yaml:"chartType,omitempty"`
	// ChartRepoURL is the Helm registry URL for external-mode apps.
	// Examples: "oci://ghcr.io/myorg/charts", "https://charts.acme.io".
	// Empty for inline-mode apps.
	ChartRepoURL string `yaml:"chartRepoURL,omitempty"`
	// ChartName is the chart name within the registry. Empty for inline.
	ChartName string `yaml:"chartName,omitempty"`
	// ChartVersion is the chart version pin. Empty for inline.
	ChartVersion string `yaml:"chartVersion,omitempty"`
}

// Constants for the ChartType values to keep callers consistent.
const (
	ChartTypeInline   = "inline"
	ChartTypeExternal = "external"
)

// PreviewAppMetadata is written as app.yaml for each preview instance.
// The previews ApplicationSet reads clusterServer and namespace from here.
type PreviewAppMetadata struct {
	AppName       string `yaml:"appName"`
	PreviewName   string `yaml:"previewName"`
	Project       string `yaml:"project"`
	Template      string `yaml:"template"`
	ClusterServer string `yaml:"clusterServer"`
	Namespace     string `yaml:"namespace"`
}

const (
	argoAppSetAPIVersion = "argoproj.io/v1alpha1"
	previewEnvType       = "preview"
)
