package gitops

import (
	"strings"
)

// AppSetEnv parameterises one environment in an ApplicationSet.
// Each instance maps to one cluster in the env/cluster-centric Model B layout.
type AppSetEnv struct {
	// EnvName is the logical environment name, e.g. "staging".
	EnvName string
	// ClusterServer is the Kubernetes API server URL for this environment's cluster.
	// Written as spec.destination.server in generated Applications.
	ClusterServer string
	// NamespacePattern is the domain.Environment.NamespacePattern value.
	// Tokens: {app}, {env}, {project}. Empty → default "{app}-{env}".
	NamespacePattern string
	// BaseDomain is the ingress base domain for apps in this environment,
	// e.g. "staging.acme.com". Used in values.yaml generation, not in the AppSet itself.
	BaseDomain string
}

// AppSetOptions carries shared configuration for all ApplicationSet builders.
type AppSetOptions struct {
	// ArgoCDNamespace is the namespace where ApplicationSet objects are created.
	// Defaults to "argocd".
	ArgoCDNamespace string
	// TargetRevision is the Git ref ApplicationSets deploy. Defaults to "HEAD".
	TargetRevision string
	// SyncAutomated enables automated sync with prune and selfHeal on generated Applications.
	SyncAutomated bool
}

// ApplicationSet is a minimal, serializable representation of an ArgoCD
// ApplicationSet CRD. Only the fields required for suparShip's env/cluster-centric
// model are included.
type ApplicationSet struct {
	APIVersion string             `yaml:"apiVersion"`
	Kind       string             `yaml:"kind"`
	Metadata   ObjectMeta         `yaml:"metadata"`
	Spec       ApplicationSetSpec `yaml:"spec"`
}

// ApplicationSetSpec is the spec section of an ArgoCD ApplicationSet.
type ApplicationSetSpec struct {
	Generators []ApplicationSetGenerator `yaml:"generators"`
	Template   ApplicationSetTemplate    `yaml:"template"`
}

// ApplicationSetGenerator holds one generator configuration.
// Only the Git File generator is used in suparShip's model.
type ApplicationSetGenerator struct {
	// Git is the Git File generator configuration.
	Git *GitFileGenerator `yaml:"git,omitempty"`
}

// GitFileGenerator discovers parameterisation files in a Git repository.
// Note: the ApplicationSet git generator uses "revision" (not "targetRevision"
// which is used in Application source specs). Using the wrong field name causes
// ArgoCD to reject the ApplicationSet with "revision: Required value".
type GitFileGenerator struct {
	RepoURL  string            `yaml:"repoURL"`
	Revision string            `yaml:"revision"`
	Files    []GitFilePathSpec `yaml:"files"`
}

// GitFilePathSpec is one path glob for the Git File generator.
type GitFilePathSpec struct {
	Path string `yaml:"path"`
}

// ApplicationSetTemplate is the Application template inside an ApplicationSet.
type ApplicationSetTemplate struct {
	Metadata ObjectMeta              `yaml:"metadata"`
	Spec     ApplicationSetAppSpec   `yaml:"spec"`
}

// ApplicationSetAppSpec is the spec of Applications generated by the AppSet.
// It uses multi-source Applications (ArgoCD ≥ v2.6).
type ApplicationSetAppSpec struct {
	Project     string                      `yaml:"project"`
	Sources     []ApplicationSource         `yaml:"sources"`
	Destination ApplicationDestination      `yaml:"destination"`
	SyncPolicy  *SyncPolicy                 `yaml:"syncPolicy,omitempty"`
}

// resolveAppSetNamespace translates a domain NamespacePattern into an AppSet
// destination.namespace template string.
//
// Token mapping:
//
//	{app}      → {{name}}          (Git File generator parameter)
//	{env}      → literal envName   (constant within one per-cluster AppSet)
//	{project}  → {{project}}       (Git File generator parameter)
//
// An empty pattern falls back to "{app}-{env}" which maps to "{{name}}-{envName}".
func resolveAppSetNamespace(pattern, envName string) string {
	if pattern == "" {
		pattern = "{app}-{env}"
	}
	result := pattern
	result = strings.ReplaceAll(result, "{app}", "{{name}}")
	result = strings.ReplaceAll(result, "{env}", envName)
	result = strings.ReplaceAll(result, "{project}", "{{project}}")
	return result
}

// BuildArgoAppSet generates the per-cluster stable-environment ApplicationSet
// for one environment directory (Model B layout).
//
// The generated ApplicationSet:
//   - Uses a Git File generator that discovers all app.yaml files under
//     "gitops-output/{envName}/*/*/app.yaml" to enumerate apps.
//   - Creates multi-source Applications: one source is the Helm chart at
//     "charts/{{template}}", the other is a ref source pointing at the
//     per-app values directory for "$appvalues/values.yaml".
//   - Hardcodes spec.destination.server to env.ClusterServer (constant per AppSet).
//   - Derives spec.destination.namespace from env.NamespacePattern.
//
// BuildArgoAppSet is a pure function — identical inputs produce identical output.
func BuildArgoAppSet(env AppSetEnv, repoURL string, opts AppSetOptions) *ApplicationSet {
	if opts.ArgoCDNamespace == "" {
		opts.ArgoCDNamespace = defaultArgoCDNS
	}
	if opts.TargetRevision == "" {
		opts.TargetRevision = defaultTargetRevision
	}
	if env.ClusterServer == "" {
		env.ClusterServer = defaultDestination
	}

	nsTemplate := resolveAppSetNamespace(env.NamespacePattern, env.EnvName)

	// Source 1: values ref — checks out the ENTIRE gitops repo so $appvalues
	// resolves to the repo root. No `path` is set intentionally: when `path` is
	// set, ArgoCD 2.13 erroneously resolves $ref to the repo root anyway, so we
	// make the intent explicit and use the full path in source 2's valueFiles.
	valuesRefSource := ApplicationSource{
		RepoURL:        repoURL,
		TargetRevision: opts.TargetRevision,
		Ref:            "appvalues",
	}

	// Source 2: Helm chart; reads per-app values from the repo via $appvalues.
	// The full path is used because $appvalues resolves to the repo root (see above).
	valuesFilePath := "$appvalues/gitops-output/" + env.EnvName + "/{{project}}/{{name}}/values.yaml"
	chartSource := ApplicationSource{
		RepoURL:        repoURL,
		Path:           "charts/{{template}}",
		TargetRevision: opts.TargetRevision,
		Helm: &HelmSource{
			ReleaseName: "{{name}}",
			ValueFiles:  []string{valuesFilePath},
		},
	}

	var syncPolicy *SyncPolicy
	if opts.SyncAutomated {
		syncPolicy = &SyncPolicy{
			Automated: &AutomatedSyncPolicy{Prune: true, SelfHeal: true},
			SyncOptions: []string{"CreateNamespace=true"},
		}
	}

	return &ApplicationSet{
		APIVersion: argoAppSetAPIVersion,
		Kind:       "ApplicationSet",
		Metadata: ObjectMeta{
			Name:      env.EnvName,
			Namespace: opts.ArgoCDNamespace,
			Annotations: map[string]string{
				syncWaveAnnotation: "0",
			},
		},
		Spec: ApplicationSetSpec{
		Generators: []ApplicationSetGenerator{
			{
				Git: &GitFileGenerator{
					RepoURL:  repoURL,
					Revision: opts.TargetRevision,
					Files: []GitFilePathSpec{
						{Path: "gitops-output/" + env.EnvName + "/*/*/app.yaml"},
					},
				},
			},
		},
		Template: ApplicationSetTemplate{
			Metadata: ObjectMeta{
				Name:      "{{name}}-" + env.EnvName,
				Namespace: opts.ArgoCDNamespace,
				Labels: map[string]string{
					labelApp:     "{{name}}",
					labelProject: "{{project}}",
					labelEnv:     env.EnvName,
				},
				// Authorize the corresponding Kargo Stage to trigger ArgoCD syncs
				// for this Application. The annotation value is "<namespace>:<stage>"
				// where namespace = Kargo project namespace = suparship project name,
				// and stage = "{app}-{env}" per KargoStageName convention.
				Annotations: map[string]string{
					"kargo.akuity.io/authorized-stage": "{{project}}:{{name}}-" + env.EnvName,
				},
			},
			Spec: ApplicationSetAppSpec{
				Project:     "{{project}}",
				Sources:     []ApplicationSource{valuesRefSource, chartSource},
				Destination: ApplicationDestination{Server: env.ClusterServer, Namespace: nsTemplate},
				SyncPolicy:  syncPolicy,
			},
		},
		},
	}
}

// BuildArgoPreviewAppSet generates the previews ApplicationSet for a GitOps repo.
//
// The generated ApplicationSet:
//   - Uses a Git File generator on "gitops-output/previews/{project}/*/app.yaml".
//   - Each preview's app.yaml must contain: name, project, template, clusterServer, namespace.
//   - The destination.server and namespace come directly from the app.yaml parameters,
//     allowing previews to target any registered cluster.
//
// BuildArgoPreviewAppSet is a pure function — identical inputs produce identical output.
func BuildArgoPreviewAppSet(repoURL string, opts AppSetOptions) *ApplicationSet {
	if opts.ArgoCDNamespace == "" {
		opts.ArgoCDNamespace = defaultArgoCDNS
	}
	if opts.TargetRevision == "" {
		opts.TargetRevision = defaultTargetRevision
	}

	valuesRefSource := ApplicationSource{
		RepoURL:        repoURL,
		TargetRevision: opts.TargetRevision,
		Ref:            "previewvalues",
	}

	chartSource := ApplicationSource{
		RepoURL:        repoURL,
		Path:           "charts/{{template}}",
		TargetRevision: opts.TargetRevision,
		Helm: &HelmSource{
			ReleaseName: "{{appName}}",
			ValueFiles:  []string{"$previewvalues/gitops-output/previews/{{project}}/{{name}}/values.yaml"},
		},
	}

	var syncPolicy *SyncPolicy
	if opts.SyncAutomated {
		syncPolicy = &SyncPolicy{
			Automated: &AutomatedSyncPolicy{Prune: true, SelfHeal: true},
			SyncOptions: []string{"CreateNamespace=true"},
		}
	}

	return &ApplicationSet{
		APIVersion: argoAppSetAPIVersion,
		Kind:       "ApplicationSet",
		Metadata: ObjectMeta{
			Name:      "previews",
			Namespace: opts.ArgoCDNamespace,
			Annotations: map[string]string{
				syncWaveAnnotation: "0",
			},
		},
		Spec: ApplicationSetSpec{
		Generators: []ApplicationSetGenerator{
			{
				Git: &GitFileGenerator{
					RepoURL:  repoURL,
					Revision: opts.TargetRevision,
					Files: []GitFilePathSpec{
						{Path: "gitops-output/previews/*/*/app.yaml"},
					},
				},
			},
		},
			Template: ApplicationSetTemplate{
				Metadata: ObjectMeta{
					Name:      "{{appName}}-{{previewName}}",
					Namespace: opts.ArgoCDNamespace,
					Labels: map[string]string{
						labelApp:     "{{appName}}",
						labelProject: "{{project}}",
						labelEnv:     "{{previewName}}",
						labelEnvType: string(previewEnvType),
					},
				},
				Spec: ApplicationSetAppSpec{
					Project: "{{project}}",
					Sources: []ApplicationSource{valuesRefSource, chartSource},
					// clusterServer and namespace come from the preview's app.yaml.
					Destination: ApplicationDestination{
						Server:    "{{clusterServer}}",
						Namespace: "{{namespace}}",
					},
					SyncPolicy: syncPolicy,
				},
			},
		},
	}
}

// AppMetadata is written as app.yaml for each app in each env directory.
// The Git File generator reads these fields as template parameters.
type AppMetadata struct {
	Name     string `yaml:"name"`
	Project  string `yaml:"project"`
	Template string `yaml:"template"`
}

// PreviewAppMetadata is written as app.yaml for each preview instance.
// The previews ApplicationSet reads clusterServer and namespace from here.
type PreviewAppMetadata struct {
	AppName       string `yaml:"appName"`
	PreviewName   string `yaml:"previewName"`
	Project       string `yaml:"project"`
	Template      string `yaml:"template"`
	ClusterServer string `yaml:"clusterServer"`
	Namespace     string `yaml:"namespace"`
}

const (
	argoAppSetAPIVersion = "argoproj.io/v1alpha1"
	previewEnvType       = "preview"
)
