package gitops_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/suparcloud/suparship/internal/branding"
	"github.com/suparcloud/suparship/internal/domain"
	"github.com/suparcloud/suparship/internal/gitops"
	"github.com/suparcloud/suparship/internal/secrets"
)

// TestPublishAppFiles_PrependsGeneratedHeader verifies every per-app YAML
// the publisher writes carries the take-over header. SREs inheriting the
// repo without context should be able to open any file and immediately
// see what regenerates it.
func TestPublishAppFiles_PrependsGeneratedHeader(t *testing.T) {
	dir := t.TempDir()

	app := &domain.App{
		Name:        "nginx",
		ProjectName: "demo",
		Spec:        domain.AppSpec{Template: domain.AppTemplateRef{Name: "web-service"}},
	}
	envs := []gitops.AppPublishEnv{
		{
			EnvName: "staging", EnvType: domain.AppEnvStaging, Order: 1, Bound: true,
			Namespace: "demo-nginx-staging",
			EnvVars:   map[string]string{"X": "y"},
			ScopeKeys: gitops.ScopePresence{GlobalApp: true},
		},
	}

	p := newTestPublisher(t)
	if err := p.PublishAppFilesForTest(dir, app, envs); err != nil {
		t.Fatalf("PublishAppFilesForTest: %v", err)
	}

	files := map[string][]string{
		filepath.Join(dir, "envs", "staging", "demo", "nginx"):           {"app.yaml", "values.yaml"},
		filepath.Join(dir, "_app-resources", "staging", "demo", "nginx"): {"meta.yaml", "env-configmap.yaml", "external-secret.yaml"},
	}
	for base, names := range files {
		for _, name := range names {
			raw, err := os.ReadFile(filepath.Join(base, name))
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			if !strings.HasPrefix(string(raw), "# Generated by suparship") {
				t.Errorf("%s missing generated-by header. First 200 bytes:\n%s", name, string(raw[:min(200, len(raw))]))
			}
			if !strings.Contains(string(raw), "README.md") {
				t.Errorf("%s header missing README pointer", name)
			}
		}
	}
}

// TestSyncChart_ChartSourcesAreNotHeadered verifies bundled Helm chart
// templates do NOT carry the platform's generated-by header. Those
// templates ARE the chart's source, not platform-generated output —
// adding a preamble would mislead operators reading the chart and break
// any tooling that parses leading comments.
func TestSyncChart_ChartSourcesAreNotHeadered(t *testing.T) {
	repoDir := t.TempDir()
	tgz := buildPackagedChart(t, "demo", map[string]string{
		"Chart.yaml":            "apiVersion: v2\nname: demo\nversion: 1.0.0\n",
		"values.yaml":           "k: v\n",
		"templates/deploy.yaml": "apiVersion: apps/v1\nkind: Deployment\n",
	})
	fetcher := &fakeChartFetcher{templateName: "demo", data: tgz}

	p, err := gitops.NewPublisher(gitops.PublisherConfig{
		RepoURL:      "http://localhost/fake.git",
		ChartFetcher: fetcher,
	})
	if err != nil {
		t.Fatalf("NewPublisher: %v", err)
	}
	if err := p.SyncChartForTest(t.Context(), repoDir, "demo", ""); err != nil {
		t.Fatalf("SyncChart: %v", err)
	}

	for _, name := range []string{"Chart.yaml", "values.yaml", "templates/deploy.yaml"} {
		raw, err := os.ReadFile(filepath.Join(repoDir, "charts", "demo", name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		if strings.HasPrefix(string(raw), "# Generated by") {
			t.Errorf("chart source %s should NOT carry the platform header, got:\n%s", name, raw)
		}
	}
}

// TestPublishAppFiles_HeaderHonoursCustomBranding locks the white-label
// contract: when an operator sets a custom platform name, the header on
// every emitted file references that name, not "suparship".
func TestPublishAppFiles_HeaderHonoursCustomBranding(t *testing.T) {
	dir := t.TempDir()

	app := &domain.App{
		Name:        "nginx",
		ProjectName: "demo",
		Spec:        domain.AppSpec{Template: domain.AppTemplateRef{Name: "web-service"}},
	}
	envs := []gitops.AppPublishEnv{
		{EnvName: "staging", EnvType: domain.AppEnvStaging, Order: 1, Bound: true, Namespace: "demo-nginx-staging"},
	}

	p := newTestPublisher(t)
	p.SetOrgConfig("myorg", secrets.ResourceNaming{}, nil, branding.Config{Name: "acme-platform", LabelDomain: "platform.acme.io"}, nil, nil)
	if err := p.PublishAppFilesForTest(dir, app, envs); err != nil {
		t.Fatalf("PublishAppFilesForTest: %v", err)
	}

	raw, err := os.ReadFile(filepath.Join(dir, "envs", "staging", "demo", "nginx", "values.yaml"))
	if err != nil {
		t.Fatalf("read values.yaml: %v", err)
	}
	if !strings.HasPrefix(string(raw), "# Generated by acme-platform") {
		t.Errorf("expected acme-platform in header, got:\n%s", string(raw[:min(200, len(raw))]))
	}
	if strings.Contains(string(raw), "Generated by suparship") {
		t.Errorf("custom branding should leave no suparship traces in header, got:\n%s", string(raw[:200]))
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
