package gitops_test

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/suparcloud/suparship/internal/domain"
	"github.com/suparcloud/suparship/internal/gitops"
	"github.com/suparcloud/suparship/internal/tpl"
)

func TestTemplateConfigMirror_WriteReadRoundTrip(t *testing.T) {
	dir := t.TempDir()
	p := newTestPublisher(t)
	off := false
	reg := &tpl.TemplateRegistry{
		BuiltIn: []string{},
		External: []tpl.ExternalTemplateRepo{
			{Name: "zeta", Type: "gitcharts", RepoURL: "https://example.com/z.git", Ref: "main", Path: "charts", Namespaced: true},
			{Name: "acme", Type: "gitcharts", RepoURL: "https://example.com/a.git", Ref: "v1", Path: "charts",
				Provider: "github", ExistingSecret: "suparship-tpl-credentials-acme", Namespaced: true},
		},
		// Derived rows must NOT reach the mirror (they churn on every sync).
		Sources: []tpl.TemplateSource{{Name: "acme.web", Origin: "external", ExternalRepo: "acme", SyncedAt: "2026-09-15T10:00:00Z"}},
	}
	overrides := map[string]*domain.TemplateOverride{
		"acme.web": {
			DefaultValues:   map[string]any{"replicaCount": 2},
			EnvValues:       map[string]map[string]any{"prod": {"replicaCount": 3}},
			Metadata:        &domain.TemplateMetadataOverride{Title: "Web"},
			Disabled:        false,
			DeliveryMode:    "direct",
			DeveloperValues: []domain.ValueFieldOverride{{Path: "replicaCount", Title: "Replicas"}},
		},
		"acme.worker": {Disabled: true},
		"empty":       {},  // empty → no file
		"nil":         nil, // nil → no file
	}
	_ = off
	m := gitops.TemplateConfigFromRegistry(reg, overrides)
	if err := p.WriteTemplateConfig(dir, m); err != nil {
		t.Fatalf("WriteTemplateConfig: %v", err)
	}

	regRaw, err := os.ReadFile(filepath.Join(dir, "_platform", "template-registry.yaml"))
	if err != nil {
		t.Fatalf("registry mirror missing: %v", err)
	}
	reg1 := string(regRaw)
	if !strings.HasPrefix(reg1, "# Generated by") {
		t.Errorf("registry mirror must carry the generated-by header:\n%s", reg1)
	}
	if strings.Contains(reg1, "sources") || strings.Contains(reg1, "syncedAt") {
		t.Errorf("registry mirror must not carry derived sync rows:\n%s", reg1)
	}
	if strings.Contains(reg1, "token") {
		t.Errorf("registry mirror must not carry credentials:\n%s", reg1)
	}
	if strings.Index(reg1, "name: acme") > strings.Index(reg1, "name: zeta") {
		t.Errorf("external sources must be sorted by name:\n%s", reg1)
	}
	if !strings.Contains(reg1, "existingSecret: suparship-tpl-credentials-acme") || !strings.Contains(reg1, "namespaced: true") {
		t.Errorf("registry mirror lost source fields:\n%s", reg1)
	}
	ovDir := filepath.Join(dir, "_platform", "template-overrides")
	for _, name := range []string{"acme.web", "acme.worker"} {
		if _, err := os.Stat(filepath.Join(ovDir, name+".yaml")); err != nil {
			t.Errorf("override mirror %s missing: %v", name, err)
		}
	}
	for _, name := range []string{"empty", "nil"} {
		if _, err := os.Stat(filepath.Join(ovDir, name+".yaml")); !os.IsNotExist(err) {
			t.Errorf("empty override %s must not be mirrored (err=%v)", name, err)
		}
	}

	back, present, err := p.ReadTemplateConfig(dir)
	if err != nil || !present {
		t.Fatalf("ReadTemplateConfig: present=%v err=%v", present, err)
	}
	if len(back.External) != 2 || back.External[0].Name != "acme" || back.External[1].Name != "zeta" {
		t.Errorf("external round-trip = %+v", back.External)
	}
	if !reflect.DeepEqual(back.External[0], reg.External[1]) {
		t.Errorf("external[acme] round-trip mismatch:\n got %+v\nwant %+v", back.External[0], reg.External[1])
	}
	if len(back.Overrides) != 2 {
		t.Fatalf("overrides round-trip = %v", back.Overrides)
	}
	web := back.Overrides["acme.web"]
	if web.DefaultValues["replicaCount"] != 2 || web.EnvValues["prod"]["replicaCount"] != 3 || web.Metadata == nil || web.Metadata.Title != "Web" ||
		web.DeliveryMode != "direct" || len(web.DeveloperValues) != 1 || web.DeveloperValues[0].Path != "replicaCount" {
		t.Errorf("override round-trip mismatch: %+v", web)
	}
	if !back.Overrides["acme.worker"].Disabled {
		t.Error("disabled flag must round-trip")
	}
}

func TestTemplateConfigMirror_PrunesStaleOverridesAndAbsentTree(t *testing.T) {
	dir := t.TempDir()
	p := newTestPublisher(t)

	if _, present, err := p.ReadTemplateConfig(dir); err != nil || present {
		t.Fatalf("absent tree: present=%v err=%v", present, err)
	}

	first := gitops.TemplateConfigFromRegistry(&tpl.TemplateRegistry{}, map[string]*domain.TemplateOverride{
		"a": {Disabled: true}, "b": {Disabled: true},
	})
	if err := p.WriteTemplateConfig(dir, first); err != nil {
		t.Fatal(err)
	}
	// Something the operator dropped in by hand that isn't yaml survives; a
	// yaml file for an override that no longer exists is pruned.
	ovDir := filepath.Join(dir, "_platform", "template-overrides")
	if err := os.WriteFile(filepath.Join(ovDir, "NOTES.md"), []byte("keep"), 0o644); err != nil {
		t.Fatal(err)
	}
	second := gitops.TemplateConfigFromRegistry(&tpl.TemplateRegistry{}, map[string]*domain.TemplateOverride{"a": {Disabled: true}})
	if err := p.WriteTemplateConfig(dir, second); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(ovDir, "b.yaml")); !os.IsNotExist(err) {
		t.Errorf("stale override mirror b.yaml must be pruned (err=%v)", err)
	}
	if _, err := os.Stat(filepath.Join(ovDir, "a.yaml")); err != nil {
		t.Errorf("a.yaml must remain: %v", err)
	}
	if _, err := os.Stat(filepath.Join(ovDir, "NOTES.md")); err != nil {
		t.Errorf("non-yaml files are not ours to prune: %v", err)
	}
	back, _, err := p.ReadTemplateConfig(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(back.Overrides) != 1 || back.Overrides["a"] == nil {
		t.Errorf("overrides after prune = %v", back.Overrides)
	}
	if len(back.BuiltIn) != 0 || back.BuiltIn == nil {
		t.Errorf("builtIn must round-trip as an empty list, got %#v", back.BuiltIn)
	}
}
