{{- $web := .Values.components.web }}
{{- $host := .Values.routing.host }}
{{- $ing := $web.ingress }}
{{- if and $web.enabled $ing $host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "color-app.fullname" . }}
  labels:
    {{- include "color-app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- with $ing.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ . }}
    {{- end }}
spec:
  ingressClassName: {{ $ing.className }}
  {{- if $ing.clusterIssuer }}
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ include "color-app.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "color-app.fullname" . }}
                port:
                  name: http
{{- end }}
