apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: voiceai-livekit-retry-caller
  namespace: argocd
spec:
  generators:
    - clusters:
       values:
         branch: main
         env_path: prod
       selector:
         matchLabels:
           enabled: "true"
           env: prod
    - clusters:
        values:
          branch: staging
          env_path: staging
        selector:
          matchLabels:
            enabled: "true"
            env: staging
          matchExpressions:
            - key: platform
              operator: NotIn
              values: [eks]
    #- clusters:
    #  values:
    #    branch: staging
    #    env_path: staging-eks
    #  selector:
    #    matchLabels:
    #      enabled: "true"
    #      env: staging
    #      platform: eks
  template:
    metadata:
      name: 'voiceai-livekit-retry-caller-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        argocd.argoproj.io/sync-timeout: "600"
        notifications.argoproj.io/subscribe.on-deployed.slack: "deployments"
        notifications.argoproj.io/subscribe.on-health-degraded.slack: "alerts"
        notifications.argoproj.io/subscribe.on-sync-failed.slack: "alerts"
    spec:
      project: "{{metadata.labels.env}}-voiceai"
      source:
        repoURL: git@github.com:Bigly-Sales/biglysales-voiceai-livekit.git
        path: deploy/kustomize/retry-caller/overlays/{{values.env_path}}
        targetRevision: '{{values.branch}}'
      destination:
        server: '{{server}}'
        namespace: voiceai
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /metadata/annotations/deployment.kubernetes.io~1revision
            - /spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt
        - group: keda.sh
          kind: ScaledObject
          jsonPointers:
            - /status
        - group: autoscaling
          kind: HorizontalPodAutoscaler
          jsonPointers:
            - /status
            - /metadata/annotations/autoscaling.alpha.kubernetes.io~1conditions
            - /metadata/annotations/autoscaling.alpha.kubernetes.io~1current-metrics
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=false
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
          - Validate=true
          - CreateOnly=false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
