apiVersion: v2
name: worker
description: A suparship template chart for long-running background workers
type: application
version: 1.0.0
appVersion: "1.0.0"
annotations:
  suparship.io/values-schema-version: v1
dependencies:
  - name: suparship-common
    version: "0.1.0"
    repository: "file://../../../charts/lib/suparship-common"
