package secrets

import (
	"fmt"
	"regexp"
	"strings"
)

// ResourceNaming holds configurable naming patterns for K8s resources and
// vault items generated by suparship. All names outside suparship-system
// are vendor-neutral — no "suparship" prefix.
type ResourceNaming struct {
	// AppResource is the K8s ExternalSecret + target Secret name in app-env
	// namespaces. Tokens: {project} {app} {env}. Default: "{app}".
	AppResource string `json:"appResource,omitempty" yaml:"appResource,omitempty"`

	// ClusterSecretStore is the ClusterSecretStore name pattern.
	// Tokens: {provider} {env} {org}. Default: "{provider}-{env}".
	ClusterSecretStore string `json:"clusterSecretStore,omitempty" yaml:"clusterSecretStore,omitempty"`

	// VaultItem holds per-scope vault item title patterns.
	VaultItem ItemNaming `json:"vaultItem,omitempty" yaml:"vaultItem,omitempty"`

	// ProjectNamespace is the org-wide default pattern for project-level
	// Kubernetes namespaces. Tokens: {org}, {project}, {env}.
	// Empty: topology-aware default is applied at resolution time.
	//   Shared cluster:    "{project}-{env}" → "myproject-staging"
	//   Dedicated cluster: "{project}"       → "myproject"
	ProjectNamespace string `json:"projectNamespace,omitempty" yaml:"projectNamespace,omitempty"`

	// AppNamespace is the org-wide default pattern for app-level
	// Kubernetes namespaces. Tokens: {org}, {project}, {app}, {env}.
	// Empty: topology-aware default is applied at resolution time.
	//   Shared cluster:    "{project}-{app}-{env}" → "myproject-api-staging"
	//   Dedicated cluster: "{project}-{app}"       → "myproject-api"
	AppNamespace string `json:"appNamespace,omitempty" yaml:"appNamespace,omitempty"`
}

// ItemNaming holds configurable patterns for vault item titles, one per
// hierarchy scope. Tokens available: {org} {env} {project} {app}.
type ItemNaming struct {
	Org     string `json:"org,omitempty" yaml:"org,omitempty"`         // default: "org"
	EnvType string `json:"envType,omitempty" yaml:"envType,omitempty"` // default: "env-{env}"
	Project string `json:"project,omitempty" yaml:"project,omitempty"` // default: "{project}"
	App     string `json:"app,omitempty" yaml:"app,omitempty"`         // default: "{project}-{app}"
	AppEnv  string `json:"appEnv,omitempty" yaml:"appEnv,omitempty"`   // default: "{project}-{app}-{env}"
}

// Default patterns for each naming slot.
const (
	DefaultAppResource        = "{app}"
	DefaultClusterSecretStore = "{provider}-{env}"
	DefaultItemOrg            = "org"
	DefaultItemEnvType        = "env-{env}"
	DefaultItemProject        = "{project}"
	DefaultItemApp            = "{project}-{app}"
	DefaultItemAppEnv         = "{project}-{app}-{env}"
)

// ── Hardcoded conventions (1Password SA-driven flow) ──────────────────────
//
// Convention-based names derived from the env. Admins do not enter these.
const (
	// OnePasswordRemoteNamespace is the namespace on TARGET clusters where
	// ESO and the sealed Connect-token Secret live.
	OnePasswordRemoteNamespace = "external-secrets"
)

// NamingParams holds the concrete values that replace tokens in patterns.
type NamingParams struct {
	Org      string
	Env      string
	Project  string
	App      string
	Provider string // e.g. "1password"
}

// dns1123 validates K8s resource names (lowercase, alphanumeric, '-').
var dns1123 = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`)

// RenderPattern replaces tokens in pattern with values from params.
func RenderPattern(pattern string, params NamingParams) string {
	r := strings.NewReplacer(
		"{org}", params.Org,
		"{env}", params.Env,
		"{project}", params.Project,
		"{app}", params.App,
		"{provider}", params.Provider,
	)
	return r.Replace(pattern)
}

// ValidateRendered checks that a rendered name is valid for K8s resources.
func ValidateRendered(rendered, context string) error {
	if rendered == "" {
		return fmt.Errorf("naming: %s rendered to empty string", context)
	}
	if strings.ContainsAny(rendered, " \t\n") {
		return fmt.Errorf("naming: %s contains whitespace: %q", context, rendered)
	}
	return nil
}

// ValidateRenderedDNS1123 validates a rendered K8s resource name.
func ValidateRenderedDNS1123(rendered, context string) error {
	if err := ValidateRendered(rendered, context); err != nil {
		return err
	}
	if !dns1123.MatchString(rendered) {
		return fmt.Errorf("naming: %s is not a valid DNS-1123 name: %q", context, rendered)
	}
	return nil
}

// ValidateRenderedNamespace validates a rendered Kubernetes namespace name.
// Extends ValidateRenderedDNS1123 with the 63-character limit imposed by
// RFC 1123 for DNS label components.
func ValidateRenderedNamespace(rendered, context string) error {
	if err := ValidateRenderedDNS1123(rendered, context); err != nil {
		return err
	}
	if len(rendered) > 63 {
		return fmt.Errorf("naming: %s exceeds 63-char Kubernetes limit: %q (%d chars)", context, rendered, len(rendered))
	}
	return nil
}

// ── Effective getters ──────────────────────────────────────────────────────

func (n ResourceNaming) EffectiveAppResource() string {
	if n.AppResource != "" {
		return n.AppResource
	}
	return DefaultAppResource
}

func (n ResourceNaming) EffectiveClusterSecretStore() string {
	if n.ClusterSecretStore != "" {
		return n.ClusterSecretStore
	}
	return DefaultClusterSecretStore
}

// EffectiveProjectNamespace returns the org-wide project namespace pattern.
// Empty string means no org default is set; topology decides at resolution time.
func (n ResourceNaming) EffectiveProjectNamespace() string {
	return n.ProjectNamespace
}

// EffectiveAppNamespace returns the org-wide app namespace pattern.
// Empty string means no org default is set; topology decides at resolution time.
func (n ResourceNaming) EffectiveAppNamespace() string {
	return n.AppNamespace
}

func (n ItemNaming) EffectiveOrg() string {
	if n.Org != "" {
		return n.Org
	}
	return DefaultItemOrg
}

func (n ItemNaming) EffectiveEnvType() string {
	if n.EnvType != "" {
		return n.EnvType
	}
	return DefaultItemEnvType
}

func (n ItemNaming) EffectiveProject() string {
	if n.Project != "" {
		return n.Project
	}
	return DefaultItemProject
}

func (n ItemNaming) EffectiveApp() string {
	if n.App != "" {
		return n.App
	}
	return DefaultItemApp
}

func (n ItemNaming) EffectiveAppEnv() string {
	if n.AppEnv != "" {
		return n.AppEnv
	}
	return DefaultItemAppEnv
}

// ── Render helpers ─────────────────────────────────────────────────────────

// RenderAppResource renders the K8s resource name for an app-env namespace.
func (n ResourceNaming) RenderAppResource(params NamingParams) string {
	return RenderPattern(n.EffectiveAppResource(), params)
}

// RenderClusterSecretStore renders the ClusterSecretStore name.
func (n ResourceNaming) RenderClusterSecretStore(params NamingParams) string {
	return RenderPattern(n.EffectiveClusterSecretStore(), params)
}

// RenderVaultItem renders the vault item title for the given scope level.
func (n ResourceNaming) RenderVaultItem(level string, params NamingParams) string {
	var pattern string
	switch level {
	case LevelOrg:
		pattern = n.VaultItem.EffectiveOrg()
	case LevelEnvironment:
		pattern = n.VaultItem.EffectiveEnvType()
	case LevelProject:
		pattern = n.VaultItem.EffectiveProject()
	case LevelApp:
		pattern = n.VaultItem.EffectiveApp()
	case LevelAppEnv:
		pattern = n.VaultItem.EffectiveAppEnv()
	default:
		return level
	}
	return RenderPattern(pattern, params)
}

// Validate checks that the configured naming patterns produce valid K8s names
// and don't collide across vault item scopes when rendered with sample values.
func (n ResourceNaming) Validate() error {
	sample := NamingParams{
		Org:      "default",
		Env:      "prod",
		Project:  "acme",
		App:      "web",
		Provider: "1password",
	}

	if err := ValidateRenderedDNS1123(n.RenderAppResource(sample), "appResource"); err != nil {
		return err
	}
	if err := ValidateRenderedDNS1123(n.RenderClusterSecretStore(sample), "clusterSecretStore"); err != nil {
		return err
	}

	if n.ProjectNamespace != "" {
		r := RenderPattern(n.ProjectNamespace, sample)
		if err := ValidateRenderedNamespace(r, "projectNamespace"); err != nil {
			return err
		}
	}
	if n.AppNamespace != "" {
		r := RenderPattern(n.AppNamespace, sample)
		if err := ValidateRenderedNamespace(r, "appNamespace"); err != nil {
			return err
		}
	}

	// Vault item titles don't need DNS-1123, just non-empty/no-whitespace.
	levels := []string{LevelOrg, LevelEnvironment, LevelProject, LevelApp, LevelAppEnv}
	rendered := make(map[string]string, len(levels))
	for _, l := range levels {
		r := n.RenderVaultItem(l, sample)
		if err := ValidateRendered(r, "vaultItem."+l); err != nil {
			return err
		}
		if prev, ok := rendered[r]; ok {
			return fmt.Errorf("naming: vault item patterns collide: %s and %s both render to %q", prev, l, r)
		}
		rendered[r] = l
	}

	return nil
}
